image: node:lts

cache:
  paths:
   - node_modules/
   - .nyc_output/

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  
stages:
   - build
   - test
   - quality
   - deploy
  
build:
  stage: build
  script:
   - npm ci
  
test:
  dependencies:
   - build
  script:
   - npm run coverage
  coverage: '/Branches.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - .nyc_output/reports/
      
quality:
  stage: quality
  dependencies:
    - test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
     - .sonar/cache
  script:
     - sonar-scanner
  only:
     - master
     - merge_requests

pages:
  stage: deploy
  script:
    - mv .nyc_output/reports/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
